In [40]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

In [5]:
basedir = '_run_output_1'
sorted(os.listdir(basedir))

['couple_prob', 'divorce_prob', 'leaving_prob']

In [27]:
catdir = os.path.join(basedir, 'divorce_prob')
sorted(os.listdir(catdir))

['divorce_prob_0.0',
 'divorce_prob_0.1',
 'divorce_prob_0.2',
 'divorce_prob_0.3',
 'divorce_prob_0.4',
 'divorce_prob_0.5',
 'divorce_prob_0.6',
 'divorce_prob_0.7',
 'divorce_prob_0.8',
 'divorce_prob_0.9',
 'divorce_prob_1.0']

In [28]:
pdir = os.path.join(catdir, 'divorce_prob_0.0')
sorted(os.listdir(pdir))

['nonburn_0.005_s152745_y2000',
 'nonburn_0.005_s183236_y2000',
 'nonburn_0.005_s366725_y2000',
 'nonburn_0.005_s412125_y2000',
 'nonburn_0.005_s477025_y2000',
 'nonburn_0.005_s481850_y2000',
 'nonburn_0.005_s739784_y2000',
 'nonburn_0.005_s767514_y2000',
 'nonburn_0.005_s808225_y2000',
 'nonburn_0.005_s997948_y2000']

In [29]:
sdir = os.path.join(pdir, 'nonburn_0.005_s152745_y2000')
sorted(os.listdir(sdir))

['household_size_dynamic.csv.xz',
 'household_structure_dynamic.csv.xz',
 'stored_household.csv.xz',
 'stored_population.csv.xz',
 'stored_sex_age_stats.csv.xz',
 'thumbnails',
 'yearly_summary.csv.xz']

In [30]:
fp = os.path.join(sdir, 'stored_household.csv.xz')
df = pd.read_csv(fp)

In [31]:
df.head()

,ind,time,household_id,member,household_founded,infant,school_age,adult,retired,household_size
0,0,0,0,0;1,0,0,0,2,0,2
1,1,0,1,2;3;4;5,0,0,0,3,1,4
2,2,0,2,6;7,0,0,0,2,0,2
3,3,0,3,8;9;10;11;12,0,0,0,4,1,5
4,4,0,4,13;8137,0,0,0,2,0,2

In [13]:
basedirs = ['_run_output_1', '_run_output_2', '_run_output_3']
catdirs = ['couple_prob', 'divorce_prob', 'leaving_prob']

In [42]:
cat = catdirs[1]

dfs = []
for bdir in basedirs:
    pdirs = sorted(os.listdir(os.path.join(bdir, cat)))
    #print(pdirs)
    this_df = None
    for pdir in tqdm(pdirs, desc='prob {}'.format(bdir)):
        p = float(pdir.split('_')[-1])
        sdirs = sorted(os.listdir(os.path.join(bdir, cat, pdir)))
        #print(sdirs)
        for sdir in sdirs:
            seed = sdir.split('_')[-2]
            #print(seed)
            fp = os.path.join(bdir, cat, pdir, sdir, 'stored_household.csv.xz')
            df = pd.read_csv(fp, index_col=0)
            df = df.groupby('time')['household_id'].count().reset_index(name='no_household')
            df[cat] = p
            df['seed'] = seed
            #print(df)
            #print(df.head())
            if this_df is None:
                this_df = df
            else:
                this_df = this_df.append(df)
            #break
            #print(len(df))
        #break
    #print(this_df.head(10))
    #print(len(this_df))
    dfs.append(this_df)
    #break
len(dfs), len(dfs[0])

prob: 100%|██████████| 11/11 [00:14<00:00,  1.43s/it]
prob: 100%|██████████| 11/11 [00:12<00:00,  1.22s/it]
prob: 100%|██████████| 11/11 [00:10<00:00,  1.02s/it]

(3, 2310)

In [43]:
dfs[0]

    time  no_household  divorce_prob     seed
0      0          5226           0.0  s152745
1      1          5356           0.0  s152745
2      2          5500           0.0  s152745
3      3          5660           0.0  s152745
4      4          5785           0.0  s152745
5      5          5917           0.0  s152745
6      6          6014           0.0  s152745
7      7          6101           0.0  s152745
8      8          6162           0.0  s152745
9      9          6248           0.0  s152745
10    10          6323           0.0  s152745
11    11          6386           0.0  s152745
12    12          6423           0.0  s152745
13    13          6478           0.0  s152745
14    14          6520           0.0  s152745
15    15          6553           0.0  s152745
16    16          6588           0.0  s152745
17    17          6598           0.0  s152745
18    18          6622           0.0  s152745
19    19          6644           0.0  s152745
20    20          6664           0.0  s152745
0      0          5313           0.0  s183236
1      1          5481           0.0  s183236
2      2          5598           0.0  s183236
3      3          5714           0.0  s183236
4      4          5835           0.0  s183236
5      5          5926           0.0  s183236
6      6          6046           0.0  s183236
7      7          6136           0.0  s183236
8      8          6202           0.0  s183236
..   ...           ...           ...      ...
12    12         10770           1.0  s808225
13    13         10906           1.0  s808225
14    14         10963           1.0  s808225
15    15         11024           1.0  s808225
16    16         11116           1.0  s808225
17    17         11101           1.0  s808225
18    18         11144           1.0  s808225
19    19         11188           1.0  s808225
20    20         11120           1.0  s808225
0      0          8350           1.0  s997948
1      1          8671           1.0  s997948
2      2          9023           1.0  s997948
3      3          9309           1.0  s997948
4      4          9528           1.0  s997948
5      5          9764           1.0  s997948
6      6          9975           1.0  s997948
7      7         10152           1.0  s997948
8      8         10268           1.0  s997948
9      9         10398           1.0  s997948
10    10         10536           1.0  s997948
11    11         10654           1.0  s997948
12    12         10774           1.0  s997948
13    13         10817           1.0  s997948
14    14         10898           1.0  s997948
15    15         10987           1.0  s997948
16    16         11014           1.0  s997948
17    17         11032           1.0  s997948
18    18         11068           1.0  s997948
19    19         11051           1.0  s997948
20    20         11050           1.0  s997948

[2310 rows x 4 columns]

In [45]:
cat = catdirs[0]

for bdir in basedirs:
    pdirs = sorted(os.listdir(os.path.join(bdir, cat)))
    #print(pdirs)
    for pdir in tqdm(pdirs, desc='prob {}'.format(bdir)):
        p = float(pdir.split('_')[-1])
        sdirs = sorted(os.listdir(os.path.join(bdir, cat, pdir)))
        #print(sdirs)
        for sdir in sdirs:
            seed = sdir.split('_')[-2]
            #print(seed)
            fp = os.path.join(bdir, cat, pdir, sdir, 'stored_household.csv.xz')
            df = pd.read_csv(fp, index_col=0)
            df = df.groupby('time')['household_id'].count().reset_index(name='no_household')
            df[cat] = p
            df['seed'] = seed
            fpout = os.path.join(bdir, cat, pdir, sdir, 'summary_household.csv.xz')
            df.to_csv(fpout, index_label='ind')

prob _run_output_1: 100%|██████████| 11/11 [00:11<00:00,  1.09s/it]
prob _run_output_2: 100%|██████████| 11/11 [00:11<00:00,  1.05s/it]
prob _run_output_3: 100%|██████████| 11/11 [00:11<00:00,  1.04s/it]

In [44]:
cat = catdirs[1]

for bdir in basedirs:
    pdirs = sorted(os.listdir(os.path.join(bdir, cat)))
    #print(pdirs)
    for pdir in tqdm(pdirs, desc='prob {}'.format(bdir)):
        p = float(pdir.split('_')[-1])
        sdirs = sorted(os.listdir(os.path.join(bdir, cat, pdir)))
        #print(sdirs)
        for sdir in sdirs:
            seed = sdir.split('_')[-2]
            #print(seed)
            fp = os.path.join(bdir, cat, pdir, sdir, 'stored_household.csv.xz')
            df = pd.read_csv(fp, index_col=0)
            df = df.groupby('time')['household_id'].count().reset_index(name='no_household')
            df[cat] = p
            df['seed'] = seed
            fpout = os.path.join(bdir, cat, pdir, sdir, 'summary_household.csv.xz')
            df.to_csv(fpout, index_label='ind')

prob _run_output_1: 100%|██████████| 11/11 [00:15<00:00,  1.44s/it]
prob _run_output_2: 100%|██████████| 11/11 [00:12<00:00,  1.25s/it]
prob _run_output_3: 100%|██████████| 11/11 [00:11<00:00,  1.04s/it]

In [46]:
cat = catdirs[2]

for bdir in basedirs:
    pdirs = sorted(os.listdir(os.path.join(bdir, cat)))
    #print(pdirs)
    for pdir in tqdm(pdirs, desc='prob {}'.format(bdir)):
        p = float(pdir.split('_')[-1])
        sdirs = sorted(os.listdir(os.path.join(bdir, cat, pdir)))
        #print(sdirs)
        for sdir in sdirs:
            seed = sdir.split('_')[-2]
            #print(seed)
            fp = os.path.join(bdir, cat, pdir, sdir, 'stored_household.csv.xz')
            df = pd.read_csv(fp, index_col=0)
            df = df.groupby('time')['household_id'].count().reset_index(name='no_household')
            df[cat] = p
            df['seed'] = seed
            fpout = os.path.join(bdir, cat, pdir, sdir, 'summary_household.csv.xz')
            df.to_csv(fpout, index_label='ind')

prob _run_output_1: 100%|██████████| 11/11 [00:13<00:00,  1.31s/it]
prob _run_output_2: 100%|██████████| 11/11 [00:12<00:00,  1.14s/it]
prob _run_output_3: 100%|██████████| 11/11 [00:11<00:00,  1.01s/it]